CREATE TABLE "branches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_code" varchar(10) UNIQUE NOT NULL,
  "address" varchar(255) NOT NULL,
  "phone" varchar(20),
  "branch_type" varchar(20) NOT NULL,
  "opening_time" time DEFAULT '07:00',
  "closing_time" time DEFAULT '22:00',
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "dine_in_branches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer UNIQUE NOT NULL,
  "seating_capacity" integer NOT NULL,
  "number_of_tables" integer NOT NULL,
  "number_of_chairs" integer NOT NULL,
  "has_parking" boolean DEFAULT false,
  "service_charge_percent" decimal(4,2) DEFAULT 0,
  "has_wifi" boolean DEFAULT true
);

CREATE TABLE "delivery_branches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer UNIQUE NOT NULL,
  "delivery_radius_km" decimal(5,2) NOT NULL,
  "base_delivery_fee" decimal(10,2) NOT NULL,
  "free_delivery_min" decimal(10,2),
  "max_concurrent_orders" integer DEFAULT 20,
  "partner_apps" varchar(255)
);

CREATE TABLE "employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "full_name" varchar(100) NOT NULL,
  "phone" varchar(20) UNIQUE,
  "email" varchar(100) UNIQUE,
  "role" varchar(30) NOT NULL,
  "employee_type" varchar(20) NOT NULL,
  "hire_date" date NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "fulltime_employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer UNIQUE NOT NULL,
  "monthly_salary" decimal(10,2) NOT NULL,
  "annual_leave_days" integer DEFAULT 12,
  "health_insurance" boolean DEFAULT true,
  "social_insurance" boolean DEFAULT true,
  "contract_start" date NOT NULL,
  "contract_end" date,
  "allowance" decimal(10,2) DEFAULT 0
);

CREATE TABLE "parttime_employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer UNIQUE NOT NULL,
  "hourly_rate" decimal(10,2) NOT NULL,
  "max_hours_per_week" integer NOT NULL DEFAULT 24,
  "min_hours_per_week" integer DEFAULT 8,
  "overtime_rate" decimal(4,2) DEFAULT 1.5,
  "available_days" varchar(100),
  "preferred_shift" varchar(20)
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "category" varchar(50) NOT NULL,
  "description" text,
  "price" decimal(10,2) NOT NULL,
  "size" varchar(10),
  "is_available" boolean DEFAULT true,
  "image_url" varchar(255)
);

CREATE TABLE "customers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100) NOT NULL,
  "phone" varchar(20) UNIQUE,
  "email" varchar(100) UNIQUE,
  "registered_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branch_id" integer NOT NULL,
  "customer_id" integer,
  "employee_id" integer NOT NULL,
  "order_type" varchar(20) NOT NULL,
  "order_date" timestamp DEFAULT (now()),
  "total_amount" decimal(10,2) NOT NULL,
  "delivery_fee" decimal(10,2) DEFAULT 0,
  "service_charge" decimal(10,2) DEFAULT 0,
  "payment_method" varchar(20) NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "delivery_address" varchar(255)
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "note" text
);

COMMENT ON TABLE "branches" IS 'CHA — thông tin chung mọi chi nhánh';

COMMENT ON COLUMN "branches"."branch_code" IS 'Mã chi nhánh: CN01, CN02, ...';

COMMENT ON COLUMN "branches"."branch_type" IS 'dine_in / delivery / hybrid';

COMMENT ON TABLE "dine_in_branches" IS 'CON 1 — riêng chi nhánh tại chỗ';

COMMENT ON COLUMN "dine_in_branches"."seating_capacity" IS 'Tổng số chỗ ngồi';

COMMENT ON COLUMN "dine_in_branches"."service_charge_percent" IS 'Phụ thu phục vụ (%)';

COMMENT ON TABLE "delivery_branches" IS 'CON 2 — riêng chi nhánh giao hàng';

COMMENT ON COLUMN "delivery_branches"."delivery_radius_km" IS 'Bán kính giao hàng (km)';

COMMENT ON COLUMN "delivery_branches"."free_delivery_min" IS 'Đơn tối thiểu miễn phí ship';

COMMENT ON COLUMN "delivery_branches"."partner_apps" IS 'GrabFood / ShopeeFood / GoFood';

COMMENT ON TABLE "employees" IS 'CHA — thông tin chung mọi nhân viên';

COMMENT ON COLUMN "employees"."role" IS 'manager / barista / cashier / shipper';

COMMENT ON COLUMN "employees"."employee_type" IS 'fulltime / parttime';

COMMENT ON TABLE "fulltime_employees" IS 'CON 1 — riêng NV toàn thời gian';

COMMENT ON COLUMN "fulltime_employees"."monthly_salary" IS 'Lương tháng (VND)';

COMMENT ON COLUMN "fulltime_employees"."annual_leave_days" IS 'Ngày phép/năm';

COMMENT ON COLUMN "fulltime_employees"."contract_end" IS 'NULL nếu không thời hạn';

COMMENT ON COLUMN "fulltime_employees"."allowance" IS 'Phụ cấp hàng tháng';

COMMENT ON TABLE "parttime_employees" IS 'CON 2 — riêng NV bán thời gian';

COMMENT ON COLUMN "parttime_employees"."hourly_rate" IS 'Lương theo giờ (VND)';

COMMENT ON COLUMN "parttime_employees"."overtime_rate" IS 'Hệ số lương ngoài giờ';

COMMENT ON COLUMN "parttime_employees"."available_days" IS 'Mon,Tue,Thu,Sat';

COMMENT ON COLUMN "parttime_employees"."preferred_shift" IS 'morning / afternoon / evening';

COMMENT ON TABLE "products" IS 'Sản phẩm trong menu';

COMMENT ON COLUMN "products"."category" IS 'Cà phê / Trà / Sinh tố / Bánh ngọt';

COMMENT ON COLUMN "products"."size" IS 'S / M / L';

COMMENT ON TABLE "customers" IS 'Khách hàng thành viên';

COMMENT ON TABLE "orders" IS 'Hóa đơn tổng — ai mua, ở đâu, tổng tiền, thanh toán bằng gì';

COMMENT ON COLUMN "orders"."customer_id" IS 'NULL nếu khách vãng lai';

COMMENT ON COLUMN "orders"."order_type" IS 'dine_in / takeaway / delivery';

COMMENT ON COLUMN "orders"."payment_method" IS 'cash / card / momo / bank_transfer';

COMMENT ON COLUMN "orders"."status" IS 'pending / preparing / completed / cancelled';

COMMENT ON COLUMN "orders"."delivery_address" IS 'Chỉ khi order_type = delivery';

COMMENT ON TABLE "order_items" IS 'Từng dòng trên hóa đơn — món gì, mấy ly, giá bao nhiêu';

COMMENT ON COLUMN "order_items"."unit_price" IS 'Giá tại thời điểm mua';

COMMENT ON COLUMN "order_items"."note" IS 'Ít đường, thêm shot, không đá';

ALTER TABLE "dine_in_branches" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "delivery_branches" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fulltime_employees" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parttime_employees" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;
